name: Build WASM & Deploy GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

# Permisos requerits per a desplegar a GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-and-deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Instal·lar Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: wasm32-unknown-unknown

      - name: Instal·lar wasm-pack
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

      - name: Compilar Rust a WebAssembly
        run: wasm-pack build --target web --out-dir www/pkg

      - name: Configurar GitHub Pages
        uses: actions/configure-pages@v5

      - name: Pujar actius web (incloent www/pkg)
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'www'

      - name: Desplegar a GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
